### ISSUE TITLE
Directory Traversal Vulnerability

### ISSUE THREAD

**Issue by RaineForest** [gcarvelli/qftp#1]
I can specify any file on the system by relative path. This is a pretty big problem. We're running this on our cluster with 1000 instances at once, and now pretty SoL because of this oversight. Is there any fix planned for the future?

`raineforest@nimble:~$ telnet 129.21.92.254 5050`
`Trying 129.21.92.254...`
`Connected to 129.21.92.254.`
`Escape character is '^]'.`
`../../../../bin/bash`
`200 file found`
`Connection closed by foreign host.`
`raineforest@nimble:~$ telnet 129.21.92.254 17`
`Trying 129.21.92.254...`
`Connected to 129.21.92.254.`
`Escape character is '^]'.`
`ￏ￺￭�ﾀ￘ﾅ H__PAGEZERO(__TEXT__text__TEXﾀ__stubs__TEXTlbﾀ__stub_helper__TEXT￐^￐ﾀ__cstring__TEXT.$a￸.$__const`
`Connection closed by foreign host.`

**Comment by khipkin** [comment]
git rekt

**Comment by gcarvelli** [comment]
Thank you for this valuable input Dakota, I will look into this right away

**Comment by gcarvelli** [comment]
@khipkin k

**Comment by RaineForest** [comment]
We've already lost over 50,000 customers. A quick fix would be appreciated.

**Comment by gcarvelli** [comment]
@RaineForest I assure you security is our topmost priority, check back for a fix in 5-10 business days

**Comment by gcarvelli** [comment]
This small bug has been patched in release 0.2. Thanks for the input valuable community member!

**Comment by RaineForest** [comment]
Thanks for the responsive update! We've hemorrhaged nearly half of our user base now, but I'm sure they'll come back soon.

**Comment by khipkin** [comment]
*\* hemorrhaged
